### ISSUE TITLE
"port in use" error with Kafka GUI

### ISSUE THREAD

**Issue by benblamey** [HASTE-project/hom-2#33]
[logs-from-kafka-ui-in-kafka-ui-deployment-7fd7896dc9-whwxr.log](https://github.com/HASTE-project/hom-2/files/9259061/logs-from-kafka-ui-in-kafka-ui-deployment-7fd7896dc9-whwxr.log)

**Comment by Haoyuan-L** [comment]
Is this why I cannot forward "kafka-gui" and got a 503 error (service not available)？

**Comment by benblamey** [comment]
@Haoyuan-L probably...
